// GENERATED by dc2html.py from the builder export — do not edit.
window.HizenBackdrop = {
_vineParams(s, H) {
    return {
      y0: H * (0.34 + 0.44 * this._hash(s, 1)),
      a1: H * (0.05 + 0.09 * this._hash(s, 2)), f1: 0.0009 + 0.0011 * this._hash(s, 3), p1: 6.28 * this._hash(s, 4),
      a2: H * (0.02 + 0.04 * this._hash(s, 5)), f2: 0.003 + 0.003 * this._hash(s, 6), p2: 6.28 * this._hash(s, 7)
    };
  },
_vineY(v, x) { return v.y0 + v.a1 * Math.sin(x * v.f1 + v.p1) + v.a2 * Math.sin(x * v.f2 + v.p2); },
_daisy(ctx, x, y, R, spin, a) {
    for (let k = 0; k < 8; k++) {
      const h = this._hash(Math.round(x) + k, 71);
      const ang = spin + (k / 8) * 6.2832 + (h - 0.5) * 0.55;
      const len = R * (0.75 + 0.55 * h);
      this._leaf(ctx, x + Math.cos(ang) * R * 0.1, y + Math.sin(ang) * R * 0.1, ang, len, a * (0.7 + 0.45 * h));
    }
    ctx.beginPath(); ctx.arc(x, y, R * 0.1, 0, 6.2832);
    ctx.fillStyle = 'rgba(240,238,232,' + Math.min(1, a * 1.4).toFixed(3) + ')'; ctx.fill();
  },
_leaf(ctx, x, y, ang, len, a) {
    ctx.save(); ctx.translate(x, y); ctx.rotate(ang);
    const w = len * 0.38;
    const g = ctx.createLinearGradient(0, 0, len, 0);
    g.addColorStop(0, 'rgba(240,238,232,' + (a * 0.22).toFixed(3) + ')');
    g.addColorStop(0.6, 'rgba(240,238,232,' + (a * 0.72).toFixed(3) + ')');
    g.addColorStop(1, 'rgba(240,238,232,' + Math.min(1, a * 1.08).toFixed(3) + ')');
    ctx.fillStyle = g;
    ctx.beginPath();
    ctx.moveTo(0, 0);
    ctx.bezierCurveTo(len * 0.28, -w, len * 0.82, -w * 0.92, len, -w * 0.06);
    ctx.bezierCurveTo(len * 0.82, w * 0.92, len * 0.28, w, 0, 0);
    ctx.fill(); ctx.restore();
  },
_hash(x, y) { return ((((x * 73856093) ^ (y * 19349663)) >>> 0) % 1000) / 1000; },
_drawVines(cv, full, k) {
    const W = Math.min(6400, Math.round(window.innerWidth * 3));
    const H = Math.max(420, window.innerHeight);
    const pw = Math.round(W * k), ph = Math.round(H * k);
    if (cv.width !== pw || cv.height !== ph) { cv.width = pw; cv.height = ph; }
    const ctx = cv.getContext('2d');
    ctx.setTransform(k, 0, 0, k, 0, 0);
    ctx.clearRect(0, 0, W, H);
    const ink = a => 'rgba(240,238,232,' + Math.min(1, a).toFixed(3) + ')';
    ctx.font = '10px "IBM Plex Mono", monospace';
    const cell = 16;
    for (let gx = 0; gx < W / cell; gx++) for (let gy = 0; gy < H / cell; gy++) {
      const h = this._hash(gx + 7, gy + 3);
      if (h > (full ? 0.92 : 0.66)) continue;
      const a = full ? 0.2 + h * 0.5 : 0.07 + h * 0.11;
      ctx.fillStyle = ink(a);
      ctx.beginPath(); ctx.arc(gx * cell + cell / 2, gy * cell + cell / 2, full ? 1.3 + h * 1.7 : 1 + h * 1, 0, 6.2832); ctx.fill();
    }
    for (let s = 0; s < 10; s++) {
      const v = this._vineParams(s, H);
      ctx.beginPath(); ctx.moveTo(0, this._vineY(v, 0));
      for (let x = 6; x <= W; x += 6) ctx.lineTo(x, this._vineY(v, x));
      ctx.strokeStyle = ink(full ? 0.52 : 0.3); ctx.lineWidth = 1; ctx.stroke();
      for (let x = 60; x < W - 30; x += 88) {
        const h = this._hash(s * 97 + Math.round(x / 88), 11);
        const y = this._vineY(v, x);
        const tang = Math.atan2(this._vineY(v, x + 6) - this._vineY(v, x - 6), 12);
        if (h < 0.28) {
          if (full || h < 0.16) {
            const side = h < 0.14 ? 1 : -1;
            this._leaf(ctx, x, y, tang + side * (0.7 + 0.5 * this._hash(s, x)), 12 + 14 * this._hash(x, s), full ? 0.5 : 0.26);
          }
        } else if (h < 0.66) {
          if (full || h < 0.55) {
            const val = this._hash(Math.round(x / 7), s * 13 + 5).toFixed(2);
            const side = h < 0.47 ? -1 : 1;
            const nx = Math.cos(tang + 1.5708) * 8 * side, ny = Math.sin(tang + 1.5708) * 8 * side;
            ctx.strokeStyle = ink(full ? 0.45 : 0.26); ctx.lineWidth = 1;
            ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + nx * 0.7, y + ny * 0.7); ctx.stroke();
            ctx.fillStyle = ink(full ? 0.82 : 0.4);
            ctx.fillText(val, x + nx + (side < 0 ? -28 : 2), y + ny + 3.5);
          }
        } else if (h > 0.91) {
          if (full) this._daisy(ctx, x, y, 15 + 11 * this._hash(x, 3), 6.28 * this._hash(x, 9), 0.62);
          else {
            ctx.beginPath(); ctx.arc(x, y, 2.4, 0, 6.2832); ctx.fillStyle = ink(0.4); ctx.fill();
            this._leaf(ctx, x, y, -1.9, 9, 0.3); this._leaf(ctx, x, y, -1.2, 9, 0.3);
          }
        }
      }
    }
    for (let i2 = 0; i2 < 70; i2++) {
      if (!full && i2 % 3 !== 0) continue;
      const px = this._hash(i2, 41) * W, py = this._hash(i2, 43) * H;
      this._leaf(ctx, px, py, 6.28 * this._hash(i2, 47), 7 + 8 * this._hash(i2, 53), full ? 0.18 : 0.12);
    }
  }
};
